name: CI

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master, dev ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: ashutoshvarma/setup-ninja@master
      - name: Build
        run: ninja
      - name: Run tests
        run: ./test

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
      - uses: ashutoshvarma/setup-ninja@master
      - name: Build
        run: ninja
      - name: Run tests
        run: .\test.exe

  # clang is not good
  # gnu not available ig :((((
  # build-macos:
    # runs-on: macos-latest
#
    # steps:
      # - uses: actions/checkout@v1
      # - uses: ashutoshvarma/setup-ninja@master
      # - name: Build
        # run: ninja
      # - name: Run tests
        # run: ./test
